### ISSUE TITLE
walkRouteOverlay.removeFromMap() 方法不执行

### ISSUE THREAD

**Issue by ShineYang** [amap-demo/android-walk-route-plan#1]
执行线路规划回调时，walkRouteOverlay.removeFromMap()方法体内容并不执行，上一次线路规划的路线无法remove.

**Comment by mayan0** [comment]
这是demo调用逻辑有问题，已经修改了。
walkRouteOverlay需要在new之前调用removeFromMap，才会删除之前的路线

**Comment by ShineYang** [comment]
get
